# Lista 2 - Mineração de Dados

In [ ]:
#INSTALANDO PACOTES 

! pip install pyarrow
! pip install duckdb

### item a) Leitura do dataset

In [ ]:
import pandas as pd
import numpy as np
import pyarrow
import duckdb

#LENDO O ARQUIVO
arquivo = pd.read_csv('C:/Users/iuri_/OneDrive/Desktop/mineracao_de_dados/fakeTelegram.BR_2022.csv')
arquivo

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",5,2022-11-16 14:49:39.146502,0.1027,NaN,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,5,2022-11-16 14:49:39.847434,0.0000,NaN,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.922279,0.0000,NaN,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.992932,0.0000,NaN,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:40.064006,0.0000,NaN,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e

### item b) Removendo trava-zaps

In [ ]:
#REMOVENDO TRAVA ZAPS
arquivo = arquivo[arquivo['trava_zap'] != 1]

### item c) Exportando para arquivo Parquet

In [ ]:
#EXPORTANDO PARA PARQUET
arquivo.to_parquet('fakeTelegram.parquet')

In [ ]:
#LENDO O ARQUIVO PARQUET
arquivo = pd.read_parquet('fakeTelegram.parquet')
arquivo

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,None,None,None,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,None,None
1,2022-10-05 06:25:08,None,12283e08a2eb5789201e105b34489ee7,None,None,None,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,None,None
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,None,None,None,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,None,None
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,None,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,None,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,None,True,False,False,None,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,None,5ad5c8bbe9da93a37fecf3e5aa5b0637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",5,2022-11-16 14:49:39.146502,0.1027,NaN,575796,Url,telegram,None,25e43b6a58b848c43ad5b5f9e979822a
557582,2022-11-11 12:09:08,None,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,5,2022-11-16 14:49:39.847434,0.0000,NaN,1286443,Url,telegram,None,657949d03e4088f6b332e2686ccd3221
557583,2022-11-11 12:09:47,None,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.922279,0.0000,NaN,13294,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e
557584,2022-11-11 12:09:46,None,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.992932,0.0000,NaN,1286444,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e
557585,2022-11-11 12:09:48,None,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:40.064006,0.0000,NaN,192127,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e

### item d) Exportando para arquivo Duckdb

In [ ]:
#EXPORTANDO PARA DUCKDB
conn = duckdb.connect()
conn.register('telegram', arquivo)

### item e) Executando buscas no Duckdb

In [ ]:
#EXECUTANDO BUSCAS NO DUCKDB

querry1 = conn.execute("""SELECT COUNT(id_message) AS quantidade
                         FROM telegram
                        """).fetchdf()

querry1

   quantidade
0      557570

In [20]:
querry2 = conn.execute("""SELECT COUNT(DISTINCT id_member_anonymous) AS quantidade
                         FROM telegram
                        """).fetchdf()

querry2

   quantidade
0       14809

In [22]:
querry3 = conn.execute("""SELECT COUNT(DISTINCT id_group_anonymous) AS quantidade
                         FROM telegram
                        """).fetchdf()

querry3

   quantidade
0         178

In [24]:
querry4 = conn.execute("""SELECT COUNT(message_type) AS quantidade
                          FROM telegram
                          WHERE message_type = 'Texto'
                        """).fetchdf()

querry4

   quantidade
0      224966

In [ ]:
querry5 = conn.execute("""SELECT COUNT(message_type) AS quantidade
                          FROM telegram
                          WHERE message_type != 'Texto'
                        """).fetchdf()

querry5

   quantidade
0      332604

In [ ]:
querry6 = conn.execute("""SELECT media_type, COUNT(id_message) AS quantidade
                          FROM telegram
                          WHERE media_type IS NOT NULL
                          GROUP BY media_type ORDER BY quantidade DESC
                        """).fetchdf()

querry6

                                 media_type  quantidade
0                                 image/jpg      200440
1                                       url      100856
2                                 video/mp4       18497
3   application/vnd.android.package-archive        7159
4                           application/pdf        2850
..                                      ...         ...
62                                image/wma           1
63                                image/m4a           1
64                                image/flv           1
65                                 image/gz           1
66   image/b0cf97975368a5ebec0eb3d25e695e1c           1

[67 rows x 2 columns]

In [ ]:
#subitem 6
querry7 = conn.execute("""SELECT media_type, COUNT(id_message) AS quantidade
                          FROM telegram
                          WHERE media_type IS NOT NULL
                          GROUP BY media_type ORDER BY quantidade DESC
                        """).fetchdf()

querry7

In [ ]:
#subitem 12
querry8 = conn.execute("""SELECT media_url, COUNT(media_url) AS quantidade
                          FROM telegram
                          WHERE has_media_url = TRUE
                          GROUP BY media_url ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry8

                                            media_url  quantidade
0                                   t.me/alexeconomia        4159
1     https://youtube.com/c/especulandoosfatosoficial        1607
2                                   t.me/fimtaproximo        1581
3                              t.me/+EWlGMatRZGg3OTlh        1419
4                        https://youtu.be/qbTzhB0akt8        1160
5                        https://youtu.be/zDuOoyhyN-4        1022
6                              t.me/+ewZIPdZ42vEyNzJh         772
7                https://t.me/canalselvabrasiloficial         709
8                        https://youtu.be/4DHk9KZ01HM         660
9                           T.me/Arthur_Senna_Trader2         640
10                       https://youtu.be/x2uiakywcrI         576
11                             t.me/+bseuTTFOO8c5YWFh         515
12                           youtube.com/AlexEconomia         445
13                          https://t.me/Ovetoroculto         394
14                     https://t.me/+DnJpx-HxNCFkMmUx         390
15  https://noticias.uol.com.br/politica/ultimas-n...         388
16          https://t.me/ContagemDeVotosPRO_BOLSONARO         375
17                         https://t.me/ipiranoticias         358
18  https://instagram.com/exercito_oficial?igshid=...         355
19  https://youtube.com/channel/UCVvPvyD-zdnTTapAb...         349
20                       https://youtu.be/wGpTY8GH568         332
21                       https://youtu.be/u-ZGL90PfeI         282
22                             t.me/+L987ddlsBJVkYzAx         273
23                        t.me/direitologicoparatodos         262
24  https://scriptsamp.forumeiros.com/t16154-enque...         260
25                           https://lulaflix.com.br/         255
26                       https://youtu.be/aJ7uw_d-dUI         250
27                 https://t.me/misteriosdomundobruno         249
28                  http://ligapatriota.blogspot.com/         244
29                       https://youtu.be/a4IjtAhIVbI         222

In [ ]:
#Criando uma nova coluna que extrai somente o dominio de um url completo.
from urllib.parse import urlparse


def extract_domain(url):
    if pd.isna(url):
        return None
    if not url.startswith(('http://', 'https://')):
        url = 'http://' + url  # Add scheme if missing
    parsed = urlparse(url)
    domain = parsed.netloc.lower()
    if domain.startswith('www.'):
        domain = domain[4:]  # Remove www.
    return domain

arquivo['domain'] = arquivo['media_url'].apply(extract_domain)
conn.register('telegram', arquivo)
arquivo[arquivo['domain'].notnull()]

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5,domain
9,2022-10-05 06:29:48,a7e85072244cae15446c9d517dc01a1a,b8a8737812c7fd7d3e0bdbb65ef6306f,None,None,www.marketingdigitalparavencer.com.br,False,True,False,O Deputado Federal pelo NOVO e que foi candida...,5,2022-10-05 06:29:49.901419,-0.8779,0.035876,7248,Texto,telegram,None,None,marketingdigitalparavencer.com.br
11,2022-10-05 06:32:21,None,2ff252ad4422e11a6a8abfaa747abb55,None,None,t.me/alexeconomia,False,True,False,Gazprom da Rússia: Retomamos o fornecimento de...,5,2022-10-05 06:32:29.06454,-0.1531,NaN,48922,Texto,telegram,None,None,t.me
16,2022-10-05 06:35:42,d49f81df0c75d1d72bee6c5b2d707da0,e3988dfe85b2ba2fa0499a428dd8a20a,None,None,https://youtube.com/c/especulandoosfatosoficial,False,True,False,🚨Olá SEJA bem vindo(a) ..- ao grupo Especuland...,5,2022-10-05 06:35:49.661204,0.8074,0.018574,451729,Texto,telegram,None,None,youtube.com
18,2022-10-05 06:37:09,047b67065d87ac7d8db977ad4506b436,c8f2de56550ed0bf85249608b7ead93d,None,None,https://www.facebook.com/groups/86482768025364...,False,True,False,https://www.facebook.com/groups/86482768025364...,5,2022-10-05 06:37:29.584697,0.0000,NaN,19284,Texto,telegram,None,None,facebook.com
38,2022-10-05 06:56:01,None,0e899038fbe9196d404c90cf7ad282e0,None,None,http://lulaflix.com.br,False,True,False,PT recorre ao TSE para tirar do ar site “LulaF...,5,2022-10-05 06:56:30.615304,0.4710,0.629701,5759,Texto,telegram,None,None,lulaflix.com.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",5,2022-11-16 14:49:39.146502,0.1027,NaN,575796,Url,telegram,None,25e43b6a58b848c43ad5b5f9e979822a,terrabrasilnoticias.com
557582,2022-11-11 12:09:08,None,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,5,2022-11-16 14:49:39.847434,0.0000,NaN,1286443,Url,telegram,None,657949d03e4088f6b332e2686ccd3221,youtu.be
557583,2022-11-11 12:09:47,None,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.922279,0.0000,NaN,13294,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e,t.me
557584,2022-11-11 12:09:46,None,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.992932,0.0000,NaN,1286444,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e,t.me
557585,2022-11-11 12:09:48,None,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:40.064006,0.0000,NaN,192127,Imagem,telegram,None,a21848a61045380a6483866daed0ca0e,t.me

In [ ]:
querry9 = conn.execute("""SELECT domain, COUNT(domain) AS quantidade
                          FROM telegram
                          WHERE has_media_url = TRUE
                          GROUP BY domain ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry9

                         domain  quantidade
0                      youtu.be       52842
1                          t.me       21367
2                   youtube.com       14768
3       terrabrasilnoticias.com        8284
4                 instagram.com        6668
5   jornaldacidadeonline.com.br        4829
6                   twitter.com        4442
7           gazetabrasil.com.br        1781
8                    pleno.news        1602
9                  facebook.com        1368
10                 bitchute.com        1178
11  aliadosbrasiloficial.com.br         945
12             revistaoeste.com         931
13               kwai-video.com         863
14                    gettr.com         842
15           vistapatria.com.br         830
16      verdadecensurada.com.br         829
17       conexaopolitica.com.br         746
18                vm.tiktok.com         744
19                m.youtube.com         694
20          noticias.uol.com.br         629
21       tribunanacional.com.br         609
22                     fb.watch         573
23             apostagem.com.br         568
24            veja.abril.com.br         567
25                   rumble.com         531
26  redemption3301.blogspot.com         494
27                 g1.globo.com         444
28            chat.whatsapp.com         441
29         direitaonline.com.br         422

In [ ]:
querry10 = conn.execute("""SELECT id_member_anonymous, COUNT(id_member_anonymous) AS quantidade
                          FROM telegram
                          GROUP BY id_member_anonymous ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry10

                 id_member_anonymous  quantidade
0   abe534d581ec6d552243d6955d3c3cd8       12289
1   1665e22b0f564cd46d343f7677014821        5452
2   1ac091b8ed5c4e42383f1b4ff4cc9b2d        5060
3   c743967449a387ad2c1c7e03b2c45b36        3019
4   e7998863ac2a40086657fab4a6b463c9        1928
5   e8fd8fee8c39342d37993775da7756d5        1706
6   2f4be6244ede15b46e8329a2c975be30        1620
7   d49f81df0c75d1d72bee6c5b2d707da0        1571
8   4f7d493f0f6222d56e5b19a4f7c336cc        1447
9   773b9bd5b02a2e96f9d732c29bfcb663        1411
10  c052c859b42c5a1923c22f5a201de746        1386
11  f233cf8b1d4ede06f32199a7e0081bf5        1273
12  56b8359fd127312651b80b8ed8030085        1206
13  e5e3e38d433016adf62ea34432853a3c        1095
14  fa582c9e95da255e44f4c198d0daf3df        1031
15  3e49fd40fd973ee1b8f1a6d58feb4a54         990
16  cf061f911f3df59fca0b3f084abe88cc         981
17  f4561a21fb26cfbebf48dcd5c557f82f         952
18  40743c2ea5139af088057763ab069b1a         949
19  bd7859770eef94f34d0344a5397c5443         944
20  beb77036ff26e78865da19310ac95169         897
21  50cc2b20a3c2c24ce68bb2c0554ddae1         852
22  fbbbfb737acb18812f7de2400841abc3         847
23  79fa510c3ab44548d903284ab9162c9d         833
24  566ba5c5eeeac2fc18b65965c3909a1f         787
25  27f5833380581fab3453c1acd26427d5         750
26  22da7e558d613074dc701f8a40bc955b         735
27  74ce4ba0ef6c0d51e6a508b0bb2d37b8         730
28  a378e9743fa3ca297df321cfa0e7cf6a         714
29  cb68fd028cfdfc837248144a18673ffb         714

In [ ]:
querry11 = conn.execute("""SELECT id_member_anonymous, COUNT(id_member_anonymous) AS quantidade
                          FROM telegram
                          WHERE message_type = 'Texto'
                          GROUP BY id_member_anonymous ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry11

                 id_member_anonymous  quantidade
0   abe534d581ec6d552243d6955d3c3cd8       12289
1   c743967449a387ad2c1c7e03b2c45b36        2867
2   1665e22b0f564cd46d343f7677014821        2480
3   d49f81df0c75d1d72bee6c5b2d707da0        1571
4   f233cf8b1d4ede06f32199a7e0081bf5        1022
5   e8fd8fee8c39342d37993775da7756d5         699
6   a378e9743fa3ca297df321cfa0e7cf6a         598
7   7696d5103cdb8ac352d748a1db1126b0         560
8   26b496125c8b6773bce453e14f172430         502
9   7d41f1a2df245b0cc870f546c2aead0b         483
10  b4ce87d44421ef3d2c4710051df5fe40         478
11  e7998863ac2a40086657fab4a6b463c9         430
12  1ac091b8ed5c4e42383f1b4ff4cc9b2d         428
13  22722eeb9ae4be8f45581e69eb707be4         409
14  a398999c55f8d6f0c65760522ae12e45         402
15  065039508ed6e276e5f092dd22eaef94         373
16  39ee10516124280a22f1798f2a41f9a7         372
17  e5e3e38d433016adf62ea34432853a3c         361
18  8e72a8fbc76263914ed485ab068396fd         335
19  8294d1400a9c3b268b23bb3047185101         331
20  27f5833380581fab3453c1acd26427d5         330
21  3bc8b1ec90f8f23e38a6d953e8faab61         328
22  f4561a21fb26cfbebf48dcd5c557f82f         302
23  7eeb43c85fe3d87c2de509828d213d80         298
24  566ba5c5eeeac2fc18b65965c3909a1f         292
25  2e08ae4c6ec1973e7ec515d3b0ba50d0         265
26  b97ba0dcff3661f08b46de507fa3d5f6         258
27  9b34f45b5f8af4c37ba9ec1ebe2e3606         249
28  4a498818da925377eff2606a260cfa45         248
29  773b9bd5b02a2e96f9d732c29bfcb663         244

In [ ]:
querry12 = conn.execute("""SELECT id_member_anonymous, COUNT(id_member_anonymous) AS quantidade
                          FROM telegram
                          WHERE message_type != 'Texto'
                          GROUP BY id_member_anonymous ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry12

                 id_member_anonymous  quantidade
0   1ac091b8ed5c4e42383f1b4ff4cc9b2d        4632
1   1665e22b0f564cd46d343f7677014821        2972
2   e7998863ac2a40086657fab4a6b463c9        1498
3   2f4be6244ede15b46e8329a2c975be30        1489
4   4f7d493f0f6222d56e5b19a4f7c336cc        1359
5   c052c859b42c5a1923c22f5a201de746        1289
6   773b9bd5b02a2e96f9d732c29bfcb663        1167
7   56b8359fd127312651b80b8ed8030085        1079
8   e8fd8fee8c39342d37993775da7756d5        1007
9   3e49fd40fd973ee1b8f1a6d58feb4a54         965
10  fa582c9e95da255e44f4c198d0daf3df         914
11  cf061f911f3df59fca0b3f084abe88cc         802
12  50cc2b20a3c2c24ce68bb2c0554ddae1         801
13  beb77036ff26e78865da19310ac95169         797
14  40743c2ea5139af088057763ab069b1a         758
15  e5e3e38d433016adf62ea34432853a3c         734
16  bd7859770eef94f34d0344a5397c5443         717
17  79fa510c3ab44548d903284ab9162c9d         704
18  22da7e558d613074dc701f8a40bc955b         672
19  c923ed78ee5cf2ecbd55ab500f19a5d4         664
20  f4561a21fb26cfbebf48dcd5c557f82f         650
21  aed9b55fd26f99a58a11c11fa2af80ef         644
22  cb68fd028cfdfc837248144a18673ffb         621
23  74ce4ba0ef6c0d51e6a508b0bb2d37b8         615
24  fbbbfb737acb18812f7de2400841abc3         605
25  51110a75091ae9ede718a0b434227368         596
26  cd6979b0b5265f08468fa1689b6300ce         584
27  38e1ca63cd9f9c6ad762d833bcb1b118         580
28  fb4a5f8c3319aa373d868e69589481f9         570
29  d36c39da7c9705400e5056e033363b65         555

In [ ]:
querry13 = conn.execute("""SELECT text_content_anonymous, COUNT(text_content_anonymous) AS quantidade
                          FROM telegram
                          GROUP BY text_content_anonymous ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry13

                               text_content_anonymous  quantidade
0   This community was blocked in Brazil following...       17422
1                                          Rough_sex🙈        1134
2                                           Anal sex🙈        1118
3   سکس مردان ازبک با زن انگلیسی با این vpn از سای...        1019
4                        https://youtu.be/qbTzhB0akt8         758
5                        https://youtu.be/zDuOoyhyN-4         712
6   فیلم سوپر با زیرنویس فارسی ببین😍😍\nبا این فیلت...         632
7                                              Rough😱         570
8                                Foto de Nélia Barros         548
9   We had no choice but to remain in the shadows....         480
10                                            Rough😨💦         471
11  https://t.me/canalselvabrasiloficial\nSELVA BR...         461
12                              Foto de Marcelo Rossi         421
13                                    HD (1080p) sex🙈         418
14  🇮🇷 سکس با دختر 14 ساله را در سایتهای پورن\nبیی...         400
15                       https://youtu.be/x2uiakywcrI         395
16                                           A.n.a.l🙈         390
17                                      Vídeo de Rosa         384
18  https://noticias.uol.com.br/politica/ultimas-n...         378
19  "E conhecereis a verdade, e a verdade vos libe...         367
20                                       Lesbian👩‍❤‍👩         359
21  Bem vindo(a) ao grupo Ipirá Notícias. \n\nComp...         358
22                                      Vaginall sex🙈         354
23                       https://youtu.be/4DHk9KZ01HM         341
24                       https://youtu.be/wGpTY8GH568         234
25                                       Vaginal sex🙈         233
26                                 Foto de susy silva         202
27                       https://youtu.be/u-ZGL90PfeI         202
28                     Vídeo de AVANY FERREIRA MULLER         195
29                       https://youtu.be/aJ7uw_d-dUI         191

In [ ]:
querry14 = conn.execute("""SELECT text_content_anonymous, COUNT(DISTINCT id_group_anonymous) AS quantidade
                          FROM telegram
                          WHERE text_content_anonymous IS NOT NULL
                          GROUP BY text_content_anonymous ORDER BY quantidade DESC LIMIT 30
                        """).fetchdf()

querry14

                               text_content_anonymous  quantidade
0   This community was blocked in Brazil following...          59
1   BOA NOITE A TODOS. O QUE EU VOU DIZER É SÉRIO ...          36
2   Hoje às 18 horas no canal Inteligência Ltda do...          35
3                                              [USER]          32
4                        https://youtu.be/zDuOoyhyN-4          31
5                        https://youtu.be/qbTzhB0akt8          30
6   *ATENÇÃO* \n🚨🚨🚨🚨🚨🚨🚨🚨🚨\n\n*CHAMADA URGENTE* Pat...          29
7   OS PTISTAS NÃO QUER QUE AGENTE MOSTRE QUE VOTO...          29
8   DE NADA IRÁ ADIANTAR FISCALIZAR AS URNAS, SE N...          29
9   Ajudem a subir a #JanonesAmigoDePedofilo\n\nPo...          29
10  BRASILEIROS, PIOR DE QUE VOCÊS PERDEREM SEUS C...          28
11  OS ELEITORES QUE JA ENVIOU, NÃO PRECISA MAIS E...          28
12            Enviando por email requerimento GSI.pdf          27
13          https://t.me/ContagemDeVotosPRO_BOLSONARO          27
14  Prezados Brasileiros Patriotas, \nSaudações,\n...          27
15  Enviando por email Habeas corpus - STJ - POVO-...          27
16  Os grupos 'MEU VOTO É BOLSONARO 22' ficaram ab...          27
17  SE VOCÊ ACREDITA QUE BOLSONARO GANHOU NO PRIME...          27
18  Enviando por email REPRESENTAÇÃO - Prisão M...          27
19  Lançaram o Lulaflix, uma coletânea com o que d...          27
20                                  Vídeo de Maurício          27
21  Queridos amigos Patriotas, \n\nSegue o sentime...          27
22  PESSOAL, POSTE SEU COMPROVANTE DE VOTO.\n\nSER...          27
23  - Contra tudo e contra todos, tivemos no 1° tu...          26
24  QUANDO ESTIVER ZERO MEMBROAQUI, TEREMOS A CERT...          26
25  CONTAGEM PÚBLICA DE VOTOS PRO BOLSONARO22 2⁰ T...          26
26  PNDH3\n\nPROGRAMA DO PT (UMA DESGRAÇA PARA O B...          25
27  JAIR BOLSONARO é o Presidente da República. El...          25
28  O LULA É ⓘ 𝘾𝙤𝙢𝙚𝙣𝙩𝙖́𝙧𝙞𝙤 𝙍𝙚𝙢𝙤𝙫𝙞𝙙𝙤 𝙋𝙚𝙡𝙤 𝙏𝙧𝙞𝙗𝙪𝙣𝙖𝙡 ...          25
29  QUERIDOS PATRÍOTAS, ESSA É A NOSSA SEGUNDA E Ú...          25

In [ ]:
querry15 = conn.execute("""SELECT 
    id_member_anonymous,
    text_content_anonymous,
    COUNT(*) AS quantidade
    FROM telegram
    WHERE text_content_anonymous IS NOT NULL AND id_member_anonymous IS NOT NULL
    GROUP BY id_member_anonymous, text_content_anonymous
    HAVING COUNT(*) > 1
    ORDER BY quantidade DESC
    """).fetchdf()

querry15

,id_member_anonymous,text_content_anonymous,quantidade
0,f233cf8b1d4ede06f32199a7e0081bf5,This community was blocked in Brazil following...,838
1,c743967449a387ad2c1c7e03b2c45b36,This community was blocked in Brazil following...,532
2,7696d5103cdb8ac352d748a1db1126b0,This community was blocked in Brazil following...,530
3,1665e22b0f564cd46d343f7677014821,Bem vindo(a) ao grupo Ipirá Notícias. \n\nComp...,357
4,a398999c55f8d6f0c65760522ae12e45,This community was blocked in Brazil following...,308
...,...,...,...
18771,dc39875173cd163c8333eca91eea8d5d,"Literalmente. 4 ovos, farinha, fermento… por a...",2
18772,42a6693a589231f64443c82ad4a3ee07,A PAZ DO SENHOR AMADOS EM CRISTO JESUS E A SU...,2
18773,55234d0a5296a9eacc4c7f59ec47e93a,O KOURY ESTÁ TRAINDO A DIREITA!! VÃO VOTAR SI...,2
18774,e6285164857a0eae6f5ec10f5075a698,A pior coisa para a colaboração de um crescime...,2
18775,7eeb43c85fe3d87c2de509828d213d80,Bolsonaro está proibido de dizer que PT votou ...,2

In [ ]:
querry16 = conn.execute("""SELECT 
    id_member_anonymous,
    text_content_anonymous,
    COUNT(DISTINCT id_group_anonymous) AS quantidade
    FROM telegram
    WHERE text_content_anonymous IS NOT NULL AND id_member_anonymous IS NOT NULL
    GROUP BY id_member_anonymous, text_content_anonymous
    HAVING COUNT(DISTINCT id_group_anonymous) > 1
    ORDER BY quantidade DESC
    """).fetchdf()

querry16

,id_member_anonymous,text_content_anonymous,quantidade
0,a7840e7844020149e197272748965862,ALERTA\nESSE GRUPO FOI CRIADO PELA ESQUERDA CO...,16
1,326d0a2f1bc5a1ede446fcf5dc31ff2e,💣💥((((( URGENTÍSSIMO )))))💥💣\nESSE GRUPO É UMA...,14
2,326d0a2f1bc5a1ede446fcf5dc31ff2e,💣💣💣💥💥🔰BOMBA BOMBA🔰💥💥💣💣💣\nVCS ESTÃO ACHANDO QUE...,12
3,29dda76df3384c28a07e8bad1ee9ceed,BOA NOITE A TODOS. O QUE EU VOU DIZER É SÉRIO ...,11
4,4e93f1d3c83fd6041314517363b14ed5,Pessoal não envie seus comprovantes de votação...,10
...,...,...,...
13204,6fc0dfd5d251ec06347e88acabcd011c,https://youtu.be/1Azf4nVG1NE,2
13205,c052c859b42c5a1923c22f5a201de746,URGENTE - Augusto Nunes é DISPENSADO do Pingo ...,2
13206,4f53935b8199850bf4c6fb3b2fde6b04,https://youtu.be/S4Z_JPHRJQA,2
13207,abe534d581ec6d552243d6955d3c3cd8,"Welcome, Neto\n\n🔸 [USER] — professional tool ...",2
13208,584b05446c0afec7298ccd5c0a11fa0a,Não caiam e não percam um minuto nessa históri...,2

In [ ]:
#subitem 22
querry17 = conn.execute("""SELECT DISTINCT text_content_anonymous, score_sentiment
    FROM telegram
    ORDER BY score_sentiment DESC
    LIMIT 30
    """).fetchdf()

querry17

                               text_content_anonymous  score_sentiment
0   Shemoneh Esreh – Amidá – A Grande Oração\n\n ,...           0.9992
1   Pensa direita, não é correto compartilhar um v...           0.9990
2   MENTIROSA!!!\n\n\nPensa direita, não é correto...           0.9990
3   בונה ירושלים, Bo'ne Yetrushalayim - Benção da ...           0.9989
4   Os Sete Samurais \n \nQuando falamos sobre For...           0.9988
5   MANIFESTO À NAÇÃO BRASILEIRA\n\nEM DEFESA DO B...           0.9987
6   BOM DIA A TODOS. ENTENDO QUE ESTAMOS VIVENDO D...           0.9986
7   Olá ,\n\nUM AMIGO ME PERGUNTOU EM QUEM EU VOTE...           0.9986
8   Uma forma bem legal\nPara quem ainda não sabe ...           0.9985
9    \nA Viva Esperança\n\nDepois das saudações in...           0.9985
10  “Paz!”\nObrigada amados meus, por mais esta An...           0.9984
11  Yom Ha-Shishi (O SEXTO DIA)?\n\nE agora, sem m...           0.9984
12  VOCÊ USA A SUA SABEDORIA ESPIRITUAL?\n\nA prát...           0.9984
13  *Cincoin community!* Junte-se ao futuro que ho...           0.9983
14  Salmo 136\n\nRendei graças ao Eterno porque el...           0.9983
15  Sobre Fxcapitalgrowth\n  FCAPITAGRWTH.COM é de...           0.9981
16  Louve a Deus em Todos os Momentos\n\n\n\nImagi...           0.9978
17  PLANOS INICIAIS\n\n  SAQUES DE LUCROS SÃO DENT...           0.9978
18  🍞 ORANDO A PALAVRA DIARIAMENTE🍷\n\nDevocional ...           0.9978
19  A gente come feijão puro feijão puro feijão pu...           0.9978
20  Deus é bom o tempo todo\n\nCom que frequência ...           0.9978
21  ⚠️🆙AS MARCAS DE UMA FÉ VITORIOSA\n\nEstá escri...           0.9978
22  2 Crônicas 6\nSalomão fala ao povo\n6 Então Sa...           0.9977
23  Vamos ver um texto aqui?\n\nQuero provar pra v...           0.9976
24  As cinco  virgens prudentes que receberam as c...           0.9976
25  Ao Criador,\n\nCriador de todas as Possibilida...           0.9975
26  GOSTAR?\n\nOlá,\nUm amigo perguntou-me: \nEm q...           0.9975
27  AS MESMAS COISAS SUCEDEM AOS JUSTOS  E INJUSTO...           0.9975
28  Pois bem, os discípulos ficam a noite toda ten...           0.9974
29  E se eu lhe disser que a democracia uma fraude...           0.9974

In [ ]:
querry18 = conn.execute("""SELECT DISTINCT text_content_anonymous, score_sentiment
    FROM telegram
    ORDER BY score_sentiment 
    LIMIT 30
    """).fetchdf()

querry18

                               text_content_anonymous  score_sentiment
0   CAPITÃOZINHO DE MERDA 💩\nCAPITÃOZINHO DE MERDA...          -1.0000
1   Intervenção é meu pau na tua mão\nIntervenção ...          -0.9999
2   Gente, a Zambelli nos abandonou! Traiu a nossa...          -0.9999
3   E nós aqui nos sacrificando, aguentando sol, c...          -0.9999
4   ai ta na rua da um joinha 👍Quem ai ta na rua d...          -0.9999
5   Intervenção é meu pau na tua mão\nIntervenção ...          -0.9999
6   ME CÚ NO PAU DO BOLSONARO \nME CÚ NO PAU DO BO...          -0.9999
7   fraude fraude fraude fraude fraude fraude frau...          -0.9999
8   a rua da um joinha 👍Quem ai ta na rua da um jo...          -0.9998
9   a na rua da um joinha 👍Quem ai ta na rua da um...          -0.9998
10  na rua da um joinha 👍Quem ai ta na rua da um j...          -0.9998
11  nha 👍Quem ai ta na rua da um joinha 👍Quem ai t...          -0.9998
12  a rua da um joinha 👍Quem ai ta na rua da um jo...          -0.9998
13  a rua da um joinha 👍Quem ai ta na rua da um jo...          -0.9998
14  ta na rua da um joinha 👍Quem ai ta na rua da u...          -0.9998
15  ai ta na rua da um joinha 👍Quem ai ta na rua d...          -0.9998
16  ha 👍Quem ai ta na rua da um joinha 👍Quem ai ta...          -0.9998
17  na rua da um joinha 👍Quem ai ta na rua da um j...          -0.9998
18  Quem ai ta na rua da um joinha 👍Quem ai ta na ...          -0.9998
19  inha 👍Quem ai ta na rua da um joinha 👍Quem ai ...          -0.9998
20  Sobre a morte como política global e a necessi...          -0.9998
21  OS COVARDES E ANTI PATRIOTAS BOLSONARISTAS\n\n...          -0.9997
22  OS COVARDES E ANTI PATRIOTAS BOLSONARISTAS\n\n...          -0.9997
23  FRAUDE FRAUDE FRAUDE FRAUDE FRAUDE FRAUDE FRAU...          -0.9996
24  Precisamos nos unir imediatamente, todos os ca...          -0.9996
25  O capitão já jogou a toalha. Acordem.\nChega d...          -0.9994
26  EU PAU Ó 🫴🫴🫴🫴🫴🫴🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷ATENÇÃO !!!!!!! 🚨...          -0.9994
27  *Leandro Ruschel:*\n\nO curioso caso do presid...          -0.9993
28  VOU FAZER MELHOR...,VOU TE DAR APNAS 100 MOTIV...          -0.9993
29  FRAUDE FRAUDE FRAUDE FRAUDE FRAUDE FRAUDE FRAU...          -0.9992

In [ ]:
querry19 = conn.execute("""SELECT 
    id_member_anonymous,
    SUM(score_sentiment) AS total_sentiment
FROM telegram
WHERE score_sentiment IS NOT NULL AND id_member_anonymous IS NOT NULL
GROUP BY id_member_anonymous
ORDER BY total_sentiment DESC
                        LIMIT 1""").fetchdf()

querry19

                id_member_anonymous  total_sentiment
0  1665e22b0f564cd46d343f7677014821        3105.8447

In [ ]:
querry2O = conn.execute("""SELECT 
    id_member_anonymous,
    SUM(score_sentiment) AS total_sentiment
FROM telegram
WHERE score_sentiment IS NOT NULL AND id_member_anonymous IS NOT NULL
GROUP BY id_member_anonymous
ORDER BY total_sentiment 
                        LIMIT 1""").fetchdf()

querry2O

                id_member_anonymous  total_sentiment
0  c743967449a387ad2c1c7e03b2c45b36        -333.2689

In [ ]:
querry21 = conn.execute("""SELECT 
    text_content_anonymous,
    LENGTH(text_content_anonymous) AS text_length
FROM telegram
WHERE text_content_anonymous IS NOT NULL 
GROUP BY text_content_anonymous
ORDER BY text_length DESC 
                        LIMIT 30""").fetchdf()

querry21

                               text_content_anonymous  text_length
0   Trecho do livro “Prática da Conspiração A Agen...         4096
1   1: Naqueles dias não havia melech em Yisra-EL;...         4096
2   COMO O SOCIALISMO DESTRUIU A VENEZUELA EM POUC...         4096
3   1: Sansão foi a Gaza, e viu ali uma prostituta...         4096
4   1: Aconteceu também naqueles dias, quando não ...         4096
5   CCCCCCCCCCCCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHHHHOO...         4096
6   PROPOSTAS DE BOLSONARO PARA 2023 - POSTADAS AG...         4096
7   [Encaminhado de FYI-Brasil (Sú)]\n🚨ELEIÇÕES DE...         4096
8   ROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CA...         4096
9   1 – A Estratégia da Distração.\n\nO elemento p...         4095
10  Vamos lá... \nPra não perder o costume, mais u...         4095
11  Sobre a morte como política global e a necessi...         4095
12  [USER]⚠️⚠️DIVULGEM O MÁXIMO POSSÍVEL \n\nVAMOS...         4095
13  🔴 ALERTA TOTAL 🆘️ 💣 YAHU E YAHUSHUA São Merda ...         4094
14  PERNAMBUCO ⚽️🎄 Prefeitura do Recife abre inscr...         4094
15  "Baumer, Lorenzo",,"033, 033 (l)","www.lorenzb...         4093
16  SUGESTÃO DE PAUTA \n\n*Festival Canoa Blues 20...         4093
17  Apenas dois estrangeiros puderam subir ao pala...         4093
18  ✳️❇️⚜️⚓⚜️❇️✳️\n\nELEIÇÕES 2022- DIVULGADO O ES...         4093
19  Amados!\nOs olhos do mundo estavam voltados pa...         4093
20  Atenção! Atenção! Atenção! O Administrador do ...         4093
21  Atenção! Atenção! Atenção! O Administrador do ...         4093
22  Lula e a VARIG”\nSenhoras e senhores!!!\nVejam...         4093
23  Antonieta de Barros foi excepcional. Está entr...         4093
24  ♨️ ESCÂNDALO ♨️\n\n💣ELEIÇÕES 2022💣 \n\nDIVULGA...         4093
25  *๘๘๘๘๘๘๘๘* *๕๕๕๕๕๕๕๕* *๘๘๘๘๘๘๘๘* *๘๘๘๘๘๘๘๘* *๕...         4092
26  PETISTAS COMENDO MULHER D QUEM TÁ NOS BLOQUEIO...         4092
27  OLE OLE OLE OLAAAA LULA LULAAAAAOLE OLE OLE OL...         4092
28  ME CÚ NO PAU DO BOLSONARO \nME CÚ NO PAU DO BO...         4092
29  ┻┳|―-∩\n┳┻|　　ヽ.   Filhos e\n┻┳|　●   |   Pais e...         4092

In [ ]:
querry22 = conn.execute("""SELECT 
    text_content_anonymous,
    LENGTH(text_content_anonymous) AS text_length
FROM telegram
WHERE text_content_anonymous IS NOT NULL 
GROUP BY text_content_anonymous
ORDER BY text_length 
                        LIMIT 30""").fetchdf()

querry22

   text_content_anonymous  text_length
0                       !            1
1                       🫠            1
2                       …            1
3                       🫢            1
4                       🙃            1
5                       😄            1
6                       😂            1
7                       🐑            1
8                       .            1
9                       😁            1
10                      🚨            1
11                      👌            1
12                      ☄            1
13                      🌩            1
14                      🤡            1
15                      🫣            1
16                      😳            1
17                      🙏            1
18                      '            1
19                      👀            1
20                      😓            1
21                      f            1
22                      Ⓜ            1
23                      🙄            1
24                      ❓            1
25                      😉            1
26                      🤯            1
27                      🙂            1
28                      😕            1
29                      🔜            1

In [ ]:
querry23 = conn.execute("""SELECT 
    CAST(date_message AS DATE) AS data,
    COUNT(id_message) AS quantidade
FROM telegram
GROUP BY data
ORDER BY quantidade DESC LIMIT 1""").fetchdf()

querry23

        data  quantidade
0 2022-10-02       25243

In [ ]:
querry24 = conn.execute(""" SELECT text_content_anonymous
                            FROM telegram
                            WHERE text_content_anonymous ILIKE '%CRIMINOSA%' OR
                            text_content_anonymous ILIKE '%FACÇÃO%'
                        """).fetchdf()

querry24

                                 text_content_anonymous
0     Pensem!!!!!!'Se Houve fraude  ,Nada foi feito ...
1     A juíza substituta da 6ª Vara Criminal de Lond...
2     esse desgraçado veta pronunciamento da vacina ...
3     TSE ORGANIZAÇÃO CRIMINOSA DO PT.... acorda pov...
4     o engraçado é que institutos de pesquisas crim...
...                                                 ...
1178  *DESCOBERTA DE GOLPE DE ESTADO DISFARÇADO DE E...
1179  *DESCOBERTA DE GOLPE DE ESTADO DISFARÇADO DE E...
1180  *DESCOBERTA DE GOLPE DE ESTADO DISFARÇADO DE E...
1181  *DESCOBERTA DE GOLPE DE ESTADO DISFARÇADO DE E...
1182  Justiça solta advogadas do PCC acusadas de par...

[1183 rows x 1 columns]

In [ ]:
querry25 = conn.execute(""" SELECT text_content_anonymous
                            FROM telegram
                            WHERE text_content_anonymous ILIKE '%segurança%'
                        """).fetchdf()

querry25

                                 text_content_anonymous
0     🌳 Mato Grosso intensifica ações contra crimes ...
1     ⚡️🇧🇷 Actus Liberandi - Ordem De Cristo 🇧🇷\n\n✨...
2     ⚡️🇧🇷 Actus Liberandi - Ordem De Cristo 🇧🇷\n\n✨...
3     No Telegram entrem em Configurações > Privacid...
4     No Telegram entrem em Configurações > Privacid...
...                                                 ...
2795  Profissão médica instada a dizer às mulheres a...
2796  TSE, o relatório das Forças Armadas e o caso M...
2797  TSE, o relatório das Forças Armadas e o caso M...
2798  ✅ Notícias do Dia - Ano 6  n° 2183\nDia 11 de ...
2799  O mês de outubro registrou arrecadação de R$ 8...

[2800 rows x 1 columns]